"dependencies":
  - changed-files:
      - any-glob-to-any-file: ["pnpm-lock.yaml"]

"languages":
  - changed-files:
      - any-glob-to-any-file:
          - "src/languages/*"
          - "src/languages/**/*"
